### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by skhe** [ewen0930/PyCharm-Chinese#2]
`jar` 包放进 `lib` 之后，就变成这样。

![中文乱码](http://ww3.sinaimg.cn/large/005PneI2gw1f7oceviwuyj311y0lcwl8.jpg)

试了另一条 Issue 里面提供的，也试了自己编译的。都是这样。

**Comment by ewen0930** [comment]
不知道什么问题，有其他遇到同样问题的同学吗？

**Comment by sssir** [comment]
我也遇到了
![image](https://cloud.githubusercontent.com/assets/23093040/21746562/7b4872dc-d584-11e6-8e4c-f240facd7fe8.png)

**Comment by ewen0930** [comment]
@skhe @sssir

1. 我检查了一下代码，PASSOLO 默认输出的系统编码GB2312，我改了一个UTF-8版本，可以帮我测试一下
http://pan.baidu.com/s/1cw1cPC

2. 注意点两位都是的都是win10，可以按下面提示设置一下，看是否能好
http://jingyan.baidu.com/article/870c6fc3132cebb03fe4be22.html

**Comment by skhe** [comment]
@ewen0930 我这边能正常显示了，谢谢开发者！我把 utf-8 的包放进去之后就可以了，至于第二个，我的系统默认就是简体中文。

**Comment by sssir** [comment]
@ewen0930 确实有用了，非常感谢！
