### ISSUE TITLE
想贡献力量，请问有机翻工具么？或者能帮忙改个吗？

### ISSUE THREAD

**Issue by Zyx-A** [ewen0930/PyCharm-Chinese#5]
想贡献力量，但尝试后发现留空的键值太多，全部人工翻译，我发现很慢，上一个版本的还没翻译完，下一个版本就又出来了。
所以想找个机翻工具，然后人工校对修改不适宜的词语，这样就能快很多。
但我始终没找到合适的机翻工具。只找到类似的工具：https://github.com/westlinkin/AndroidLocalizationer 。
这个工具是适用于Android的 xml 文件，但我不会 java。如果你也没有合适的机翻工具，能否麻烦改改这个代码，使之匹配规则适用于 properties 文件。
感激不尽！

**Comment by ewen0930** [comment]
我是使用 Passolo 做的翻译，并不需要太了解java；
1、首先在网上找一份 Passolo 的使用说明了解一下
2、把原有语言包【lib/resources_en.jar】解压后，用Passolo创建中文翻译，把里面的 .properties 资源文件添加到翻译列表；新增【中文翻译】
3、再把我的 resources_zh.jar 解压，用Passolo扫描对应的目录即可 ……
4、输出 打包；（有待你自己研究和学习）

**Comment by ewen0930** [comment]
不要期望全部翻译，界面里本身有大量词汇和语句，资源文件里并没有；
有些词汇翻译了，会影响到软件的功能；
目前的翻译保证理想的可视效果，同时不影响使用即可；

**Comment by Zyx-A** [comment]
Passolo中，你的“生成目标文件”是怎么配置的？为什么我这边始终都是utf-8的普通中文样式，而不是ascii的/uxxxx样式？
我的JAVA选项中，“给来源属性文件编码”设置的是“自动检测”；“给目标属性文件编码”设置的是“与源文件相同”；并勾选“写入BOM给Unicode编码的目标文件”、“避免所有大于0x7f的字符作为\uxxxx”、“使用静态资源名称‘子串’给费档案文件”
![2017-12-07 01-00-10](https://user-images.githubusercontent.com/18498974/33674286-009c9826-daea-11e7-9368-ddfcfcad73b9.png)

**Comment by ewen0930** [comment]
我一直没搞懂Passolo转码问题！在2009里是可以自动转的，2015和2016里我一直没找到这个功能；现在是用命令转的，比如：native2ascii  -encoding utf8 messages\ActionsBundle_zh_CN.properties messages\ActionsBundle_zh_CN.properties

**Comment by Zyx-A** [comment]
经过不断尝试，找到一个还可一用的设置方法：
注意及配置要点：

1. **必须将“给来源属性文件编码”设置为“ANSI”**，且**必须勾选“避免所有大于0x7f的字符作为\uxxxx”**
2. 配置完成后，**必须要点一下“设为默认值”按钮**。
3. 设为默认值后，需要将当前项目（即将 xxx.lpu 文件及 xxx.lpu.Files 文件夹）全部删掉，然后重新创建项目，此时才是应用的最新配置，否则需要手动一个个文件的修改过来。

配置样式见截图：
![2017-12-07 15-42-51](https://user-images.githubusercontent.com/18498974/33703970-66de2c3c-db65-11e7-903f-2a1a33f9bae4.png)

我使用这个配置，生成了好几个项目，发现都是\uxxxx格式。

另外我发现无论是否勾选“写入BOM给Unicode编码的目标文件”，好像都没区别，不知道是不是我的理解有错误。勾选前后生成的文件大小都是一样的，并没有什么BOM字节。    Orz

**Comment by ewen0930** [comment]
感谢，试验了一下，确实有效；
只有Unicode文件，才可以标记BOM，既然输出文件选了“ANSI”，所以就不存在写入BOM的问题了；
这是我的理解
